/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;

/**
 *
 * @author User
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        icono = new javax.swing.JLabel();
        imagentext = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        namelogo1 = new javax.swing.JLabel();
        iconolog1 = new javax.swing.JLabel();
        registrotext = new javax.swing.JLabel();
        usuariotextreg = new javax.swing.JLabel();
        usu_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contraseñatext = new javax.swing.JLabel();
        con_field = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        confirtxt = new javax.swing.JLabel();
        conf_field = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        cedutxt = new javax.swing.JLabel();
        cedu_field = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        correotxt = new javax.swing.JLabel();
        correo_field = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        registB = new javax.swing.JPanel();
        registrar_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icono.setBackground(new java.awt.Color(255, 255, 255));
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logos Servicio Técnico Simple Blanco y Negro (1).png"))); // NOI18N
        jPanel1.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 170));

        imagentext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/image.png"))); // NOI18N
        jPanel1.add(imagentext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        jPanel2.setBackground(new java.awt.Color(43, 43, 61));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        namelogo1.setFont(new java.awt.Font("Roboto Black", 2, 14)); // NOI18N
        namelogo1.setForeground(new java.awt.Color(255, 255, 255));
        namelogo1.setText("PARTENGINE");

        iconolog1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/image (1).png"))); // NOI18N

        registrotext.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        registrotext.setForeground(new java.awt.Color(255, 255, 255));
        registrotext.setText("Registro");

        usuariotextreg.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        usuariotextreg.setForeground(new java.awt.Color(255, 255, 255));
        usuariotextreg.setText("Usuario");

        usu_field.setBackground(new java.awt.Color(43, 43, 61));
        usu_field.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        usu_field.setForeground(new java.awt.Color(153, 153, 153));
        usu_field.setText("Ingrese su nombre de usuario");
        usu_field.setBorder(null);
        usu_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usu_fieldMousePressed(evt);
            }
        });
        usu_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usu_fieldActionPerformed(evt);
            }
        });

        contraseñatext.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        contraseñatext.setForeground(new java.awt.Color(255, 255, 255));
        contraseñatext.setText("Contraseña");

        con_field.setBackground(new java.awt.Color(43, 43, 61));
        con_field.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        con_field.setForeground(new java.awt.Color(153, 153, 153));
        con_field.setText("jPasswordField1");
        con_field.setBorder(null);
        con_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                con_fieldMousePressed(evt);
            }
        });
        con_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_fieldActionPerformed(evt);
            }
        });

        confirtxt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        confirtxt.setForeground(new java.awt.Color(255, 255, 255));
        confirtxt.setText("Confirmar contraseña");

        conf_field.setBackground(new java.awt.Color(43, 43, 61));
        conf_field.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        conf_field.setForeground(new java.awt.Color(153, 153, 153));
        conf_field.setText("jPasswordField1");
        conf_field.setBorder(null);
        conf_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                conf_fieldMousePressed(evt);
            }
        });
        conf_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conf_fieldActionPerformed(evt);
            }
        });

        cedutxt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        cedutxt.setForeground(new java.awt.Color(255, 255, 255));
        cedutxt.setText("Cédula");

        cedu_field.setBackground(new java.awt.Color(43, 43, 61));
        cedu_field.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cedu_field.setForeground(new java.awt.Color(153, 153, 153));
        cedu_field.setText("Ingrese su numero de cédula o identificación");
        cedu_field.setBorder(null);
        cedu_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cedu_fieldMousePressed(evt);
            }
        });
        cedu_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedu_fieldActionPerformed(evt);
            }
        });

        correotxt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        correotxt.setForeground(new java.awt.Color(255, 255, 255));
        correotxt.setText("Correo");

        correo_field.setBackground(new java.awt.Color(43, 43, 61));
        correo_field.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        correo_field.setForeground(new java.awt.Color(153, 153, 153));
        correo_field.setText("Ingrese su correo electronico");
        correo_field.setBorder(null);
        correo_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correo_fieldMousePressed(evt);
            }
        });
        correo_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo_fieldActionPerformed(evt);
            }
        });

        registB.setBackground(new java.awt.Color(102, 51, 255));
        registB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registBMouseExited(evt);
            }
        });

        registrar_btn.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        registrar_btn.setForeground(new java.awt.Color(255, 255, 255));
        registrar_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrar_btn.setText("REGISTRAR");
        registrar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrar_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrar_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrar_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout registBLayout = new javax.swing.GroupLayout(registB);
        registB.setLayout(registBLayout);
        registBLayout.setHorizontalGroup(
            registBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        registBLayout.setVerticalGroup(
            registBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registrar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(89, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(contraseñatext)
                                        .addGap(248, 248, 248))
                                    .addComponent(con_field, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(usu_field)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(usuariotextreg)
                                        .addGap(281, 281, 281)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3)
                                    .addComponent(conf_field, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cedutxt)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cedu_field, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(correotxt)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(correo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(namelogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(registrotext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(iconolog1)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namelogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconolog1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrotext, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariotextreg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usu_field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseñatext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(con_field, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirtxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conf_field, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cedutxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cedu_field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correotxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 510, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usu_fieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usu_fieldMousePressed
        if (usu_field.getText().equals("Ingrese su nombre de usuario")){
            usu_field.setText("");
            usu_field.setForeground(Color.white);
        }
        if (String.valueOf(con_field.getPassword()).isEmpty()) {
            con_field.setText("jPasswordField1");
            con_field.setForeground(new Color(153, 153, 153));
        }
        if (String.valueOf(conf_field.getPassword()).isEmpty()) {
            conf_field.setText("jPasswordField1");
            conf_field.setForeground(new Color(153, 153, 153));
        }
        if (cedu_field.getText().isEmpty()) {
            cedu_field.setText("Ingrese su numero de cédula o identificación");
            cedu_field.setForeground(new Color(153, 153, 153));
        }
        if (correo_field.getText().isEmpty()) {
            correo_field.setText("Ingrese su correo electronico");
            correo_field.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_usu_fieldMousePressed

    private void usu_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usu_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usu_fieldActionPerformed

    private void con_fieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_con_fieldMousePressed
        if (String.valueOf(con_field.getPassword()).equals("jPasswordField1")) {
            con_field.setText("");
            con_field.setForeground(Color.white);
        }
        if (usu_field.getText().isEmpty()) {
            usu_field.setText("Ingrese su nombre de usuario");
            usu_field.setForeground(new Color(153, 153, 153));
        }
        if (String.valueOf(conf_field.getPassword()).isEmpty()) {
            conf_field.setText("jPasswordField1");
            conf_field.setForeground(new Color(153, 153, 153));
        }
        
        if (cedu_field.getText().isEmpty()) {
            cedu_field.setText("Ingrese su numero de cédula o identificación");
            cedu_field.setForeground(new Color(153, 153, 153));
        }
        if (correo_field.getText().isEmpty()) {
            correo_field.setText("Ingrese su correo electronico");
            correo_field.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_con_fieldMousePressed

    private void con_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_fieldActionPerformed

    private void conf_fieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conf_fieldMousePressed
        if (String.valueOf(conf_field.getPassword()).equals("jPasswordField1")) {
            conf_field.setText("");
            conf_field.setForeground(Color.white);
        }
        if (con_field.getText().isEmpty()) {
            con_field.setText("jPasswordField1");
            con_field.setForeground(new Color(153, 153, 153));
        }
        if (usu_field.getText().isEmpty()) {
            usu_field.setText("Ingrese su nombre de usuario");
            usu_field.setForeground(new Color(153, 153, 153));
        }
        if (cedu_field.getText().isEmpty()) {
            cedu_field.setText("Ingrese su numero de cédula o identificación");
            cedu_field.setForeground(new Color(153, 153, 153));
        }
        if (correo_field.getText().isEmpty()) {
            correo_field.setText("Ingrese su correo electronico");
            correo_field.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_conf_fieldMousePressed

    private void conf_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conf_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conf_fieldActionPerformed

    private void cedu_fieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedu_fieldMousePressed
         if (cedu_field.getText().equals("Ingrese su numero de cédula o identificación")){
            cedu_field.setText("");
            cedu_field.setForeground(Color.white);
        }
        if (String.valueOf(con_field.getPassword()).isEmpty()) {
            con_field.setText("jPasswordField1");
            con_field.setForeground(new Color(153, 153, 153));
        }
        if (usu_field.getText().isEmpty()) {
            usu_field.setText("Ingrese su nombre de usuario");
            usu_field.setForeground(new Color(153, 153, 153));
        }
        if (String.valueOf(conf_field.getPassword()).isEmpty()) {
            conf_field.setText("jPasswordField1");
            conf_field.setForeground(new Color(153, 153, 153));
        }
        if (correo_field.getText().isEmpty()) {
            correo_field.setText("Ingrese su correo electronico");
            correo_field.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_cedu_fieldMousePressed

    private void cedu_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedu_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedu_fieldActionPerformed

    private void correo_fieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correo_fieldMousePressed
          if (correo_field.getText().equals("Ingrese su correo electronico")){
            correo_field.setText("");
            correo_field.setForeground(Color.white);
        }
        if (String.valueOf(con_field.getPassword()).isEmpty()) {
            con_field.setText("jPasswordField1");
            con_field.setForeground(new Color(153, 153, 153));
        }
        if (usu_field.getText().isEmpty()) {
            usu_field.setText("Ingrese su nombre de usuario");
            usu_field.setForeground(new Color(153, 153, 153));
        }
        if (String.valueOf(conf_field.getPassword()).isEmpty()) {
            conf_field.setText("jPasswordField1");
            conf_field.setForeground(new Color(153, 153, 153));
        }
        
        if (cedu_field.getText().isEmpty()) {
            cedu_field.setText("Ingrese su numero de cédula o identificación");
            cedu_field.setForeground(new Color(153, 153, 153));
        }
        
    }//GEN-LAST:event_correo_fieldMousePressed

    private void correo_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo_fieldActionPerformed

    private void registrar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_btnMouseClicked
        login cambio2 = new login();
        cambio2.setVisible(true);
        this.dispose();    }//GEN-LAST:event_registrar_btnMouseClicked

    private void registrar_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_btnMouseEntered
        registB.setBackground(new Color(156, 106, 208));
    }//GEN-LAST:event_registrar_btnMouseEntered

    private void registrar_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar_btnMouseExited
        registB.setBackground(new Color(102, 51, 255));
    }//GEN-LAST:event_registrar_btnMouseExited

    private void registBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registBMouseClicked
        login cambio2 = new login();
        cambio2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registBMouseClicked

    private void registBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registBMouseEntered
        registB.setBackground(new Color(156, 106, 208));
    }//GEN-LAST:event_registBMouseEntered

    private void registBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registBMouseExited
        registB.setBackground(new Color(102, 51, 255));
    }//GEN-LAST:event_registBMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedu_field;
    private javax.swing.JLabel cedutxt;
    private javax.swing.JPasswordField con_field;
    private javax.swing.JPasswordField conf_field;
    private javax.swing.JLabel confirtxt;
    private javax.swing.JLabel contraseñatext;
    private javax.swing.JTextField correo_field;
    private javax.swing.JLabel correotxt;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel iconolog1;
    private javax.swing.JLabel imagentext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel loginB;
    private javax.swing.JPanel loginB1;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel loginBtn1;
    private javax.swing.JLabel namelogo1;
    private javax.swing.JPanel registB;
    private javax.swing.JLabel registrar_btn;
    private javax.swing.JLabel registrotext;
    private javax.swing.JTextField usu_field;
    private javax.swing.JLabel usuariotextreg;
    // End of variables declaration//GEN-END:variables
}
